name: CI - Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Install OpenMP for macOS to fix XGBoost/LightGBM issues
    - name: Install OpenMP on macOS
      if: runner.os == 'macOS'
      run: brew install libomp

    - name: Install hatch
      run: pip install hatch

    - name: Run linting
      run: hatch run dev:ruff check

    - name: Run formatting check
      run: hatch run dev:ruff format --check

    - name: Run tests
      run: hatch run test:cov --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: mayer79/LightSHAP
